// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright DroidVM contributors
// Additional permissions apply; see ADDITIONAL-PERMISSIONS in the repository root.
package cn.classfun.droidvm.daemon.input;

import static cn.classfun.droidvm.lib.Constants.DATA_DIR;
import static cn.classfun.droidvm.lib.utils.StringUtils.fmt;
import static cn.classfun.droidvm.lib.utils.StringUtils.pathJoin;

import android.os.IBinder;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

import cn.classfun.droidvm.daemon.server.ServerContext;
import cn.classfun.droidvm.display.IPhysicalKeyEcho;
import cn.classfun.droidvm.daemon.vm.VMInstance;
import cn.classfun.droidvm.lib.natives.UnixHelper;
import cn.classfun.droidvm.lib.store.vm.NativeDisplay;
import cn.classfun.droidvm.lib.store.vm.VMState;

/**
 * Takes the host's physical keyboards away from Android ({@code EVIOCGRAB}) and feeds their raw
 * evdev to a guest, for as long as a display console asks for it.
 *
 * <p>Why a grab rather than the key events the console already forwards: Android decides what an
 * Activity is allowed to see <em>before</em> the Activity sees it. Home, the task switcher,
 * Alt+Tab and the Meta shortcuts are taken by the window manager and never dispatched, so a guest
 * fed from {@code dispatchKeyEvent} can never be sent them, however the console is written. A
 * grabbed descriptor is the only recipient the kernel's input core hands the device's events to:
 * Android's InputReader keeps its own descriptor open and is simply never woken again, and every
 * key -- including the ones the system would have kept -- arrives here instead, as scan codes,
 * with no key layout in between.</p>
 *
 * <p>What that costs is the reason it is not simply always on: while the grab is held, that
 * keyboard cannot type into Android at all, the IME included. So the console asks for the grab
 * only while it is in front and its typing surface is one that wants no IME (see
 * {@code KeyboardMode}); switching the console to the system keyboard releases it, which is what
 * keeps Chinese and every other IME-composed input working exactly as before. Leaving the display
 * releases it too, and so does the death of the console's binder token, so no crash can leave the
 * user holding a keyboard that types nowhere.</p>
 *
 * <p>A console that asked stays armed even when it holds nothing: a Bluetooth keyboard drops and
 * comes back as whichever {@code eventN} is free, and the kernel's uevent socket is what says so.
 * The keys reach the guest through the same per-screen keyboard socket the console's on-screen
 * keys use -- this daemon is the only writer either way -- so nothing downstream has to know
 * where a key came from.</p>
 */
public final class KeyboardGrabManager {
    private static final String TAG = "KeyboardGrab";

    /** {@code struct input_event} on this ABI: 16 bytes of timeval, then type, code, value. */
    private static final int EVENT_SIZE = 24;
    private static final int EVENT_TYPE_OFFSET = 16;
    /** How many events one read may return; a burst of typing is a handful. */
    private static final int READ_EVENTS = 64;

    private static final short EV_SYN = 0x00;
    private static final short EV_KEY = 0x01;
    private static final short EV_LED = 0x11;
    private static final short SYN_REPORT = 0x00;
    /** The lamps a keyboard has: LED_NUML, LED_CAPSL, LED_SCROLLL. */
    private static final int LED_COUNT = 3;

    private static final int KEY_UP = 0;
    private static final int KEY_DOWN = 1;
    /** Auto-repeat, generated by the host's input core; see {@link #onEvents}. */
    private static final int KEY_REPEAT = 2;

    /** Codes run 0..KEY_MAX; the pressed set is one flag each. */
    private static final int KEY_COUNT = 0x300;

    /** Bytes one uevent datagram may take; the kernel's own limit is smaller. */
    private static final int UEVENT_BUFFER = 4096;
    /**
     * How long the uevent reader waits after a message before rescanning. A keyboard arrives as
     * several messages (the device, then its handlers), and a reconnecting Bluetooth keyboard as
     * a remove followed by an add -- one scan once the batch settles is both cheaper and calmer
     * than one per message.
     */
    private static final int RESCAN_DEBOUNCE_MS = 200;
    private static final String UEVENT_SUBSYSTEM_INPUT = "SUBSYSTEM=input";
    /** How long a stopping reader is waited for before the release stops caring. */
    private static final long READER_JOIN_MS = 500;

    /** Where the keys go while a console holds the keyboard. */
    private static final class Target {
        @NonNull
        final String vmId;
        @NonNull
        final String screenId;
        @Nullable
        final IBinder token;
        @Nullable
        IBinder.DeathRecipient death;
        /** The console's copy of the keys and lamps; null when it has nothing to show. */
        @Nullable
        volatile IPhysicalKeyEcho echo;

        Target(@NonNull String vmId, @NonNull String screenId, @Nullable IBinder token) {
            this.vmId = vmId;
            this.screenId = screenId;
            this.token = token;
        }
    }

    /** One grabbed keyboard: the descriptor, the thread reading it, and what it holds down. */
    private final class Grab {
        @NonNull
        final HostKeyboard device;
        final int fd;
        final int wakeReadFd;
        final int wakeWriteFd;
        final boolean[] pressed = new boolean[KEY_COUNT];
        /** Set by whoever is taking this grab down, so the reader knows its exit is expected. */
        volatile boolean stopping;
        Thread thread;

        Grab(@NonNull HostKeyboard device, int fd, int wakeReadFd, int wakeWriteFd) {
            this.device = device;
            this.fd = fd;
            this.wakeReadFd = wakeReadFd;
            this.wakeWriteFd = wakeWriteFd;
        }

        void run() {
            var buffer = new byte[EVENT_SIZE * READ_EVENTS];
            while (!stopping) {
                int ready;
                try {
                    ready = UnixHelper.nativePollIn2(fd, wakeReadFd, -1);
                } catch (Throwable e) {
                    Log.w(TAG, fmt("poll failed on %s", device), e);
                    break;
                }
                // The wake pipe, an error, or a hangup: a keyboard that went away hangs up here
                // and its node is gone with it, so there is nothing to retry.
                if (ready < 0 || (ready & 2) != 0) break;
                if ((ready & 1) == 0) continue;
                int n = UnixHelper.nativeRead(fd, buffer, buffer.length);
                if (n <= 0) {
                    if (!stopping)
                        Log.i(TAG, fmt("%s stopped reporting (read=%d); dropped", device, n));
                    break;
                }
                onEvents(this, buffer, n);
            }
            // The ungrab belongs to this thread: it is the one that can promise nothing is being
            // read out of the descriptor as it goes back to Android.
            UnixHelper.nativeEvdevGrab(fd, false);
            UnixHelper.nativeCloseFd(fd);
            UnixHelper.nativeCloseFd(wakeReadFd);
            UnixHelper.nativeCloseFd(wakeWriteFd);
            // A reader that stopped on its own is one the manager still lists; one that was told
            // to stop has already been taken off the list by the release, and must not touch the
            // lock the release is holding while it joins this thread.
            if (!stopping) forget(this);
        }

        void wake() {
            stopping = true;
            UnixHelper.nativeWrite(wakeWriteFd, new byte[]{1}, 1);
        }
    }

    /** The uevent watcher's descriptors, owned by its own thread so a stop needs no join. */
    private static final class Watcher {
        final int fd;
        final int wakeReadFd;
        final int wakeWriteFd;
        volatile boolean stopping;

        Watcher(int fd, int wakeReadFd, int wakeWriteFd) {
            this.fd = fd;
            this.wakeReadFd = wakeReadFd;
            this.wakeWriteFd = wakeWriteFd;
        }
    }

    @NonNull
    private final ServerContext ctx;
    @NonNull
    private final File configFile = new File(pathJoin(DATA_DIR, "files"), KeyboardGrabConfig.NAME);
    private final Object lock = new Object();

    /** Read without the lock by every reader thread, so the delivery target is volatile. */
    @Nullable
    private volatile Target target;
    private final Map<String, Grab> grabs = new LinkedHashMap<>();
    @NonNull
    private volatile KeyboardGrabConfig config;
    @Nullable
    private Watcher watcher;
    /**
     * The guest's keyboard lamps: which ones it has ever reported, and their state. virtio-input
     * has no way to ask, so a lamp is genuinely unknown until the guest changes it -- and what is
     * known is the guest's own view, which is the only correct one, since software in the guest
     * can toggle caps lock with no key involved.
     */
    private volatile int ledKnown;
    private volatile int ledOn;

    public KeyboardGrabManager(@NonNull ServerContext ctx) {
        this.ctx = ctx;
        this.config = KeyboardGrabConfig.load(configFile);
    }

    @NonNull
    public KeyboardGrabConfig getConfig() {
        return config;
    }

    /**
     * Replaces the settings and writes them back. Turning the feature off releases whatever is
     * held right now, because a switch that only applied to the next console would leave the
     * keyboard taken by the one already up.
     */
    public void setConfig(@NonNull KeyboardGrabConfig newConfig) throws IOException {
        newConfig.save(configFile);
        config = newConfig;
        if (!newConfig.enabled) release("disabled");
    }

    /**
     * Puts [vmId]'s [screenId] console in charge of the physical keyboards and grabs the ones
     * that are attached. [token] is the caller's binder: the grab is dropped if it dies, so a
     * console that crashed cannot leave the user without a keyboard. Returns how many keyboards
     * are held -- zero means armed and holding nothing yet, because the guest is not running or
     * no keyboard is attached, and both of those are answered later: by the VM state hook and by
     * the uevent watcher.
     */
    public int request(@NonNull String vmId, @NonNull String screenId, @Nullable IBinder token) {
        if (!config.enabled) return 0;
        var vm = ctx.getVMs().findById(vmId);
        if (vm == null) return 0;
        synchronized (lock) {
            var current = target;
            // The same console asking again is the grab it already has; a different VM or screen
            // takes it over, because only one console can be the one in front.
            if (current != null
                && (!current.vmId.equals(vmId) || !current.screenId.equals(screenId)))
                releaseLocked("taken over by another console");
            if (target == null) {
                var t = new Target(vmId, screenId, token);
                if (!linkToken(t)) return 0;
                target = t;
                Log.i(TAG, fmt("console for VM %s screen %s has the keyboard", vmId, screenId));
            }
            // A console is usually up before the guest is: it is what starts the VM. So arming
            // is not conditional on the VM running -- the keys are simply not taken until it is,
            // and the state hook below grabs them the moment it gets there. Taking a keyboard
            // away from Android any earlier would swallow keys with nowhere to put them.
            if (vm.getState() == VMState.RUNNING) grabMissingLocked();
            startWatcherLocked();
            return grabs.size();
        }
    }

    /**
     * Releases only if [vmId]'s [screenId] console is the one holding the keyboard. A console
     * that has just gone to the background says so after the one arriving has already asked --
     * Android starts the incoming Activity before it stops the outgoing one -- so an unconditional
     * release here would take the keyboard away from whoever is now in front.
     */
    public boolean releaseFor(@NonNull String vmId, @NonNull String screenId) {
        synchronized (lock) {
            var current = target;
            if (current == null
                || !current.vmId.equals(vmId) || !current.screenId.equals(screenId)) return false;
            releaseLocked("console released it");
            return true;
        }
    }

    /**
     * Registers the console's copy of the keys and lamps, or clears it with null. Only the console
     * that holds the keyboard is heard: a page that is no longer in front must not keep a feed of
     * what is being typed into the guest. Answers with the lamps as they stand, so a console that
     * has just registered does not have to wait for the next change to draw them.
     */
    public void setEcho(@NonNull String vmId, @NonNull String screenId,
                        @Nullable IPhysicalKeyEcho echo) {
        var current = target;
        if (current == null
            || !current.vmId.equals(vmId) || !current.screenId.equals(screenId)) return;
        current.echo = echo;
        if (echo != null) sendLeds(echo);
    }

    /** Hands every grabbed keyboard back to Android. Safe to call when nothing is held. */
    public void release(@NonNull String reason) {
        synchronized (lock) {
            releaseLocked(reason);
        }
    }

    /**
     * VM state hook, called from every transition. A guest that stopped, rebooted or crashed has
     * no keyboard socket any more and its console is about to go: the keys go back to Android on
     * that edge, rather than after the next keypress finds nowhere to put itself.
     */
    public void onVmState(@NonNull VMInstance vm, @NonNull VMState state) {
        var current = target;
        if (current == null || !current.vmId.equals(vm.getId().toString())) return;
        synchronized (lock) {
            // Re-read under the lock: a release may have won the race to it.
            var armed = target;
            if (armed == null || !armed.vmId.equals(vm.getId().toString())) return;
            if (state == VMState.RUNNING) {
                // The guest the console armed for is up -- including after a guest reboot, which
                // is why this is not only the first start.
                grabMissingLocked();
                return;
            }
            var reason = fmt("VM %s is %s", vm.getName(), state.name().toLowerCase());
            if (armed.token != null) {
                // A console is still in front of a guest that will very likely be back (a reboot
                // is a stop and a start): the keys go to Android meanwhile, and the console stays
                // armed. Its token is what ends this if the console goes instead.
                dropGrabsLocked(reason);
                ledKnown = 0;
                ledOn = 0;
                var echo = armed.echo;
                if (echo != null) sendLeds(echo);
            } else {
                // Nobody's console: a grab taken over IPC has no token to end it, so the VM
                // leaving RUNNING is what does.
                releaseLocked(reason);
            }
        }
    }

    /** What a settings page or the CLI shows: the settings, what is held, and what is there. */
    @NonNull
    public JSONObject status() throws JSONException {
        var obj = new JSONObject();
        obj.put("config", config.toJson());
        var current = target;
        obj.put("armed", current != null);
        if (current != null) {
            obj.put("vm_id", current.vmId);
            obj.put("screen", current.screenId);
        }
        var held = new JSONArray();
        var heldPaths = new ArrayList<String>();
        synchronized (lock) {
            for (var grab : grabs.values()) {
                held.put(grab.device.toJson());
                heldPaths.add(grab.device.path);
            }
        }
        obj.put("held", held);
        // The guest's lamps, and which of them it has said anything about at all.
        var leds = new JSONObject();
        leds.put("known", ledKnown);
        leds.put("on", ledOn);
        leds.put("num", (ledKnown & 1) == 0 ? JSONObject.NULL : ((ledOn & 1) != 0));
        leds.put("caps", (ledKnown & 2) == 0 ? JSONObject.NULL : ((ledOn & 2) != 0));
        leds.put("scroll", (ledKnown & 4) == 0 ? JSONObject.NULL : ((ledOn & 4) != 0));
        obj.put("leds", leds);
        // Everything the host has, so a page can say which keyboard is not being taken.
        var available = new JSONArray();
        for (var kb : HostKeyboard.scan()) {
            var entry = kb.toJson();
            entry.put("held", heldPaths.contains(kb.path));
            available.put(entry);
        }
        obj.put("keyboards", available);
        return obj;
    }

    // ---- grabbing ---------------------------------------------------------------------------

    /** Grabs every keyboard not already held. Caller holds {@link #lock}. */
    private int grabMissingLocked() {
        int taken = 0;
        for (var kb : HostKeyboard.scan()) {
            if (grabs.containsKey(kb.path)) continue;
            if (grabOneLocked(kb)) taken++;
        }
        return taken;
    }

    private boolean grabOneLocked(@NonNull HostKeyboard kb) {
        int fd = UnixHelper.nativeEvdevOpen(kb.path);
        if (fd < 0) {
            Log.w(TAG, fmt("cannot open %s", kb));
            return false;
        }
        int rc = UnixHelper.nativeEvdevGrab(fd, true);
        if (rc != 0) {
            // EBUSY is somebody else holding this keyboard exclusively; nothing to do but leave
            // it to them and carry on with the rest.
            Log.w(TAG, fmt("cannot grab %s: errno=%d", kb, -rc));
            UnixHelper.nativeCloseFd(fd);
            return false;
        }
        var wake = UnixHelper.nativePipe();
        if (wake == null || wake.length != 2) {
            Log.w(TAG, fmt("no wake pipe for %s; leaving it to Android", kb));
            UnixHelper.nativeEvdevGrab(fd, false);
            UnixHelper.nativeCloseFd(fd);
            return false;
        }
        var grab = new Grab(kb, fd, wake[0], wake[1]);
        var thread = new Thread(grab::run, fmt("kbd-grab-%s", new File(kb.path).getName()));
        thread.setDaemon(true);
        grab.thread = thread;
        grabs.put(kb.path, grab);
        thread.start();
        // A keyboard that joined late (or came back after a Bluetooth drop) starts with the lamps
        // the guest has already told us about, rather than whatever Android left them at.
        writeLeds(grab);
        Log.i(TAG, fmt("grabbed %s for the guest", kb));
        return true;
    }

    /**
     * Hands every grabbed keyboard back to Android but leaves the console armed. Caller holds
     * {@link #lock}.
     */
    private void dropGrabsLocked(@NonNull String reason) {
        if (grabs.isEmpty()) return;
        // Key-ups first, while the target is still there: a modifier that went down through the
        // grab and never came up leaves the guest with a Ctrl held forever, outliving both the
        // grab and the console.
        for (var grab : grabs.values()) releaseHeldKeys(grab);
        var pending = new ArrayList<>(grabs.values());
        grabs.clear();
        for (var grab : pending) grab.wake();
        for (var grab : pending) {
            // Never join the thread we are on: the escape chord releases from inside its own
            // reader, and that thread ends by itself as soon as this returns.
            if (grab.thread == null || grab.thread == Thread.currentThread()) continue;
            try {
                grab.thread.join(READER_JOIN_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
        Log.i(TAG, fmt("keyboard back to Android (%s)", reason));
    }

    /** The grabs and the console that asked for them. Caller holds {@link #lock}. */
    private void releaseLocked(@NonNull String reason) {
        var current = target;
        if (current == null && grabs.isEmpty()) return;
        dropGrabsLocked(reason);
        target = null;
        // The lamps were the guest's, and the next console may be looking at another guest.
        ledKnown = 0;
        ledOn = 0;
        unlinkToken(current);
        stopWatcherLocked();
    }

    /** A reader that ended on its own -- its keyboard went away -- is taken off the list. */
    private void forget(@NonNull Grab grab) {
        synchronized (lock) {
            grabs.remove(grab.device.path, grab);
        }
        // The console stays armed: a Bluetooth keyboard that dropped is expected back, and the
        // watcher is what grabs it again when it is.
    }

    /**
     * What the guest said about its keyboard, off the status queue crosvm writes back onto the
     * input socket: the caps/num/scroll lamps. Two things happen with it -- the lamp on the real
     * keyboard is set to match (the grabbed descriptor is opened read-write for exactly this), and
     * the console is told so it can draw the state.
     *
     * <p>Reading this at all also drains a socket the daemon used to only write to; the records
     * had nowhere to go and sat in its buffer.</p>
     */
    public void onGuestStatus(@NonNull String vmId, @NonNull String screenId,
                              @NonNull byte[] records) {
        var current = target;
        if (current == null
            || !current.vmId.equals(vmId) || !current.screenId.equals(screenId)) return;
        var in = ByteBuffer.wrap(records).order(ByteOrder.LITTLE_ENDIAN);
        int known = ledKnown;
        int on = ledOn;
        boolean changed = false;
        for (int offset = 0; offset + 8 <= records.length; offset += 8) {
            short type = in.getShort(offset);
            short code = in.getShort(offset + 2);
            int value = in.getInt(offset + 4);
            // EV_REP (the guest's repeat delay and period) also arrives here and is the host
            // keyboard's own business, not ours: the guest repeats for itself, see onEvents.
            if (type != EV_LED || code < 0 || code >= LED_COUNT) continue;
            int bit = 1 << code;
            known |= bit;
            int next = value != 0 ? (on | bit) : (on & ~bit);
            if (next != on || (known != ledKnown)) changed = true;
            on = next;
        }
        if (!changed) return;
        ledKnown = known;
        ledOn = on;
        Log.i(TAG, fmt("guest lamps: num=%s caps=%s scroll=%s",
            lampText(known, on, 1), lampText(known, on, 2), lampText(known, on, 4)));
        synchronized (lock) {
            for (var grab : grabs.values()) writeLeds(grab);
        }
        var echo = current.echo;
        if (echo != null) sendLeds(echo);
    }

    private static String lampText(int known, int on, int bit) {
        if ((known & bit) == 0) return "?";
        return (on & bit) != 0 ? "on" : "off";
    }

    /** Sets [grab]'s lamps to the guest's state, as far as the guest has said what it is. */
    private void writeLeds(@NonNull Grab grab) {
        int known = ledKnown;
        if (known == 0) return;
        var out = ByteBuffer.allocate(EVENT_SIZE * (LED_COUNT + 1)).order(ByteOrder.LITTLE_ENDIAN);
        for (int code = 0; code < LED_COUNT; code++) {
            if ((known & (1 << code)) == 0) continue;
            putInputEvent(out, EV_LED, (short) code, (ledOn & (1 << code)) != 0 ? 1 : 0);
        }
        if (out.position() == 0) return;
        putInputEvent(out, EV_SYN, SYN_REPORT, 0);
        var bytes = Arrays.copyOf(out.array(), out.position());
        UnixHelper.nativeWrite(grab.fd, bytes, bytes.length);
    }

    /** One {@code struct input_event}: an empty timeval, then type, code, value. */
    private static void putInputEvent(@NonNull ByteBuffer out, short type, short code, int value) {
        out.putLong(0).putLong(0);
        out.putShort(type).putShort(code).putInt(value);
    }

    private void sendLeds(@NonNull IPhysicalKeyEcho echo) {
        try {
            echo.onLeds(ledKnown, ledOn);
        } catch (Exception e) {
            Log.d(TAG, "console echo refused the lamps", e);
        }
    }

    // ---- events -----------------------------------------------------------------------------

    /**
     * Turns one read of {@code struct input_event}s into the 8-byte records crosvm's socket wants
     * and sends them on. Auto-repeat is dropped: the host's input core generates it for a key
     * held down and the guest's does the same for the virtio keyboard, so forwarding it would
     * repeat every held key twice over.
     */
    private void onEvents(@NonNull Grab grab, @NonNull byte[] buffer, int length) {
        var in = ByteBuffer.wrap(buffer, 0, length).order(ByteOrder.LITTLE_ENDIAN);
        var out = ByteBuffer.allocate(8 * (length / EVENT_SIZE)).order(ByteOrder.LITTLE_ENDIAN);
        // The console's copy, collected alongside: same keys, same order, sent after the guest's.
        var echoCodes = new int[length / EVENT_SIZE];
        var echoValues = new int[echoCodes.length];
        int echoCount = 0;
        boolean escape = false;
        for (int offset = 0; offset + EVENT_SIZE <= length; offset += EVENT_SIZE) {
            short type = in.getShort(offset + EVENT_TYPE_OFFSET);
            short code = in.getShort(offset + EVENT_TYPE_OFFSET + 2);
            int value = in.getInt(offset + EVENT_TYPE_OFFSET + 4);
            if (type == EV_KEY) {
                if (value == KEY_REPEAT) continue;
                if (code >= 0 && code < KEY_COUNT) {
                    synchronized (grab.pressed) {
                        grab.pressed[code] = value != KEY_UP;
                    }
                    if (value == KEY_DOWN && chordHeld(grab)) {
                        // The chord is the user talking to us, not to the guest: the key that
                        // completed it is not forwarded, and the keys already down are lifted by
                        // the release itself.
                        escape = true;
                        break;
                    }
                }
                out.putShort(type).putShort(code).putInt(value);
                echoCodes[echoCount] = code;
                echoValues[echoCount] = value;
                echoCount++;
            } else if (type == EV_SYN && code == SYN_REPORT) {
                // A frame with nothing in it is not worth a write: the guest reads events, and
                // the next real one brings its own SYN.
                if (out.position() > 0) out.putShort(type).putShort(code).putInt(value);
            }
            // Everything else (EV_MSC scan codes, LED echoes, the device's own repeat settings)
            // is host bookkeeping the guest keeps its own copy of.
        }
        if (out.position() > 0) deliver(Arrays.copyOf(out.array(), out.position()));
        // After the guest, always: what a console does with these must not be in the way of
        // typing. Oneway, so this returns before the console has looked at them.
        if (echoCount > 0) {
            var current = target;
            var echo = current == null ? null : current.echo;
            if (echo != null) {
                try {
                    echo.onKeys(Arrays.copyOf(echoCodes, echoCount),
                        Arrays.copyOf(echoValues, echoCount));
                } catch (Exception e) {
                    // A console that has gone: stop echoing rather than throwing every keypress.
                    current.echo = null;
                    Log.d(TAG, "console echo is gone; keys stay between the daemon and the guest");
                }
            }
        }
        if (escape) {
            // Off this thread: the release joins reader threads, and this is one of them.
            var t = new Thread(() -> release("escape chord"), "kbd-grab-escape");
            t.setDaemon(true);
            t.start();
        }
    }

    /** True when every key of the escape chord is down on [grab] right now. */
    private boolean chordHeld(@NonNull Grab grab) {
        var chord = config.escapeChord;
        if (chord.isEmpty()) return false;
        synchronized (grab.pressed) {
            for (var code : chord) {
                if (code < 0 || code >= KEY_COUNT || !grab.pressed[code]) return false;
            }
        }
        return true;
    }

    /** Sends an up for every key [grab] is holding, so nothing is left down in the guest. */
    private void releaseHeldKeys(@NonNull Grab grab) {
        var out = ByteBuffer.allocate(8 * (KEY_COUNT + 1)).order(ByteOrder.LITTLE_ENDIAN);
        synchronized (grab.pressed) {
            for (int code = 0; code < KEY_COUNT; code++) {
                if (!grab.pressed[code]) continue;
                grab.pressed[code] = false;
                out.putShort(EV_KEY).putShort((short) code).putInt(KEY_UP);
            }
        }
        if (out.position() == 0) return;
        out.putShort(EV_SYN).putShort(SYN_REPORT).putInt(0);
        deliver(Arrays.copyOf(out.array(), out.position()));
    }

    /** Hands finished records to the guest's keyboard, or drops them if the target has gone. */
    private void deliver(@NonNull byte[] records) {
        var current = target;
        if (current == null) return;
        var vm = ctx.getVMs().findById(current.vmId);
        if (vm == null) return;
        vm.writeNativeInput(current.screenId, NativeDisplay.KEYBOARD, records);
    }

    // ---- the console's token ----------------------------------------------------------------

    /** False when the token is already dead, which is a console not worth arming for. */
    private boolean linkToken(@NonNull Target t) {
        if (t.token == null) return true;
        t.death = () -> release("console gone");
        try {
            t.token.linkToDeath(t.death, 0);
            return true;
        } catch (Exception e) {
            Log.w(TAG, "console token is already dead; not arming", e);
            t.death = null;
            return false;
        }
    }

    private void unlinkToken(@Nullable Target t) {
        if (t == null || t.token == null || t.death == null) return;
        try {
            t.token.unlinkToDeath(t.death, 0);
        } catch (Exception ignored) {
            // Already dead, which is the one case the recipient has done its job for.
        }
        t.death = null;
    }

    // ---- hotplug ----------------------------------------------------------------------------

    /**
     * Watches the kernel's uevent socket while a console is armed, so a Bluetooth keyboard that
     * drops and reconnects -- coming back as whatever {@code eventN} is free -- is grabbed again
     * instead of typing into Android behind the console's back. Best effort: without it the grab
     * covers the keyboards that were there when the console asked, and no more.
     */
    private void startWatcherLocked() {
        if (watcher != null) return;
        int fd;
        int[] wake;
        try {
            fd = UnixHelper.nativeUeventOpen();
            if (fd < 0) {
                Log.w(TAG, "no uevent socket; a keyboard that reconnects will not be re-grabbed");
                return;
            }
            wake = UnixHelper.nativePipe();
        } catch (Throwable e) {
            Log.w(TAG, "no uevent socket; a keyboard that reconnects will not be re-grabbed", e);
            return;
        }
        if (wake == null || wake.length != 2) {
            UnixHelper.nativeCloseFd(fd);
            return;
        }
        var w = new Watcher(fd, wake[0], wake[1]);
        watcher = w;
        var thread = new Thread(() -> readUevents(w), "kbd-grab-uevent");
        thread.setDaemon(true);
        thread.start();
    }

    /**
     * Tells the watcher to stop and forgets it. Deliberately no join: the watcher's rescan wants
     * this same lock, and waiting for it here -- from inside the lock -- would stall every
     * release by however long the scan takes. The thread owns its descriptors and closes them.
     */
    private void stopWatcherLocked() {
        var w = watcher;
        if (w == null) return;
        watcher = null;
        w.stopping = true;
        UnixHelper.nativeWrite(w.wakeWriteFd, new byte[]{1}, 1);
    }

    private void readUevents(@NonNull Watcher w) {
        var buffer = new byte[UEVENT_BUFFER];
        boolean pending = false;
        while (!w.stopping) {
            int ready;
            try {
                ready = UnixHelper.nativePollIn2(
                    w.fd, w.wakeReadFd, pending ? RESCAN_DEBOUNCE_MS : -1);
            } catch (Throwable e) {
                Log.w(TAG, "uevent poll failed; hotplug re-grab is off for this console", e);
                break;
            }
            if (ready < 0 || (ready & 2) != 0) break;
            if (ready == 0) {
                // The batch settled: one scan for all of it.
                pending = false;
                rescan(w);
                continue;
            }
            if ((ready & 1) == 0) continue;
            int n = UnixHelper.nativeRead(w.fd, buffer, buffer.length);
            if (n <= 0) continue;
            if (mentionsInput(buffer, n)) pending = true;
        }
        UnixHelper.nativeCloseFd(w.fd);
        UnixHelper.nativeCloseFd(w.wakeReadFd);
        UnixHelper.nativeCloseFd(w.wakeWriteFd);
    }

    /** A uevent datagram is NUL-separated {@code KEY=VALUE}s; only the input ones are ours. */
    private static boolean mentionsInput(@NonNull byte[] buffer, int length) {
        return new String(buffer, 0, length, StandardCharsets.UTF_8)
            .contains(UEVENT_SUBSYSTEM_INPUT);
    }

    /** Grabs keyboards that appeared since the console asked. */
    private void rescan(@NonNull Watcher w) {
        synchronized (lock) {
            // The release that retired this watcher may have won the race to the lock.
            if (w.stopping || watcher != w || target == null) return;
            int taken = grabMissingLocked();
            if (taken > 0) Log.i(TAG, fmt("%d keyboard(s) joined the grab", taken));
        }
    }
}
