#!/usr/bin/env bash
# One-shot build: submodules + APK.
#
#   ./build.sh             # debug APK (default)
#   ./build.sh release     # release APK (needs signing config)
#
# Most of the work is handled by Gradle so that CI (which calls ./gradlew
# directly) and local builds behave identically:
#   * native prebuilts (VM runtime + daemons + lbx) come from the DroidVM-Prebuilts
#     submodule, or are regenerated by DroidVM-Prebuilt-Root/auto-build.py when it
#     is checked out at the repo root (see that repo's README);
#   * the terminal font is fetched by a Gradle task (best-effort; the app falls
#     back to the system monospace if it can't be downloaded).
set -euo pipefail
cd "$(dirname "$0")"

VARIANT="${1:-debug}"
case "$VARIANT" in
    debug)   GRADLE_TASK=assembleDebug;   APK_DIR=app/build/outputs/apk/debug ;;
    release) GRADLE_TASK=assembleRelease; APK_DIR=app/build/outputs/apk/release ;;
    *) echo "usage: $0 [debug|release]" >&2; exit 2 ;;
esac

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# ----------------------------------------------------- environment preflight
# The Android SDK (with NDK, for the CMake native code) is always required.
if [ -f local.properties ]; then SDK_STATUS="local.properties"; else SDK_STATUS="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-MISSING}}"; fi
log "Environment preflight:"
printf '    %-14s %s\n' "Android SDK" "$SDK_STATUS"

if [ ! -f local.properties ] && [ -z "${ANDROID_HOME:-}" ] && [ -z "${ANDROID_SDK_ROOT:-}" ]; then
    die "Android SDK not configured: set ANDROID_HOME (or ANDROID_SDK_ROOT), or create local.properties (sdk.dir=...)"
fi

# When DroidVM-Prebuilt-Root is checked out with native-util source under
# auto-build/, the Gradle build regenerates the prebuilts via auto-build.py,
# which needs the Go/Rust/clang/Python toolchains. Report and require them up
# front so the build fails fast with a clear message instead of mid-Gradle.
PREBUILT_ROOT="DroidVM-Prebuilt-Root"
prebuilt_root_active() {
    [ -f "$PREBUILT_ROOT/auto-build.py" ] && [ -d "$PREBUILT_ROOT/auto-build" ] || return 1
    # non-empty auto-build/ (ignoring a lone .gitignore) == native-util dev
    find "$PREBUILT_ROOT/auto-build" -mindepth 1 ! -name .gitignore -print -quit 2>/dev/null | grep -q .
}

if prebuilt_root_active; then
    log "$PREBUILT_ROOT detected; Gradle will regenerate prebuilts via auto-build.py"
    printf '    %-14s %s\n' "Go (golang)"  "$(have go      && go version | awk '{print $3}'      || echo 'MISSING -> https://go.dev/dl/')"
    printf '    %-14s %s\n' "Rust (cargo)" "$(have cargo    && cargo --version | awk '{print $2}'  || echo 'MISSING -> https://rustup.rs')"
    printf '    %-14s %s\n' "clang"        "$(have clang    && echo present                        || echo 'MISSING -> needed for pbridge BPF')"
    printf '    %-14s %s\n' "python3"      "$(have python3  && python3 --version | awk '{print $2}' || echo 'MISSING')"
    printf '    %-14s %s\n' "tomllib"      "$(have python3 && python3 -c 'import tomllib' 2>/dev/null && echo 'present (py3.11+)' || echo 'MISSING -> need Python 3.11+')"

    miss=""
    have go    || miss="$miss go"
    have cargo || miss="$miss cargo"
    have clang || miss="$miss clang"
    have python3 || miss="$miss python3"
    have python3 && ! python3 -c 'import tomllib' >/dev/null 2>&1 && miss="$miss python3.11+"
    [ -n "$miss" ] && die "auto-build.py needs:$miss. Install them, or remove ./$PREBUILT_ROOT to build against the published DroidVM-Prebuilts instead."
fi

# ---------------------------------------------------------------- submodules
# Includes the DroidVM-Prebuilts submodule (prebuilt artifacts) and the CMake
# submodules (libvncserver, jsoncpp, udisasm).
log "Initializing git submodules"
git submodule update --init --recursive

# --------------------------------------------------------------------- APK
log "Building APK ($GRADLE_TASK)"
./gradlew "$GRADLE_TASK"

# release has no signingConfig -> app-release-unsigned.apk; debug -> app-debug.apk.
# Just take whatever assemble produced.
APK="$(find "$APK_DIR" -maxdepth 1 -name '*.apk' 2>/dev/null | head -1)"
[ -n "$APK" ] && [ -f "$APK" ] || die "expected APK not found in $APK_DIR"
log "Done: $APK ($(du -h "$APK" | cut -f1))"
